#!/bin/bash
#
#   chrootstatus: checks the status of chroots on pkgbuild.com
#
#   Copyright (C) 2009, Daniel J Griffiths <ghost1227@archlinux.us>
#
#       This program is free software; you can redistribute it and/or modify
#       it under the terms of the GNU General Public License as published by
#       the Free Software Foundation; either version 2 of the License, or
#       (at your option) any later version.
#       
#       This program is distributed in the hope that it will be useful,
#       but WITHOUT ANY WARRANTY; without even the implied warranty of
#       MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#       GNU General Public License for more details.
#       
#       You should have received a copy of the GNU General Public License
#       along with this program; if not, write to the Free Software
#       Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston,
#       MA 02110-1301, USA.
queue=('1' '2' '3' '4')
used=0
total=0

for i in ${queue[@]}; do
	let total=total+1
	if [ -f /var/lock/queue${i} ]; then
		let used=used+1
	fi
done

open=$((${total} - ${used}))
echo
echo "${open} out of ${total} queue slots are available."
