#!/bin/bash

trap '' 2 20

MUSER=$(echo $HOME | sed -e 's|/home/||')

if [ "$EUID" != "0" ]; then
	echo 'This script must be run as root.'
	exit 1
fi

echo 'updating PKGBUILD.com local database'
yes | pacman -Syu

echo 'updating x86_64 chroots'
pacman -Syy --config /etc/pacman.x86_64

echo 'updating i686 chroots'
pacman -Syy --config /etc/pacman.i686

echo "Last update performed by $MUSER at $(date +'%H%M') on $(date +'%D')" >> /var/log/chrootupdate.log
