#!/bin/bash
#
#   chrootstatus: checks the status of chroots on pkgbuild.com
#
#   Copyright (C) 2009, Daniel J Griffiths <ghost1227@archlinux.us>
#
#       This program is free software; you can redistribute it and/or modify
#       it under the terms of the GNU General Public License as published by
#       the Free Software Foundation; either version 2 of the License, or
#       (at your option) any later version.
#       
#       This program is distributed in the hope that it will be useful,
#       but WITHOUT ANY WARRANTY; without even the implied warranty of
#       MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#       GNU General Public License for more details.
#       
#       You should have received a copy of the GNU General Public License
#       along with this program; if not, write to the Free Software
#       Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston,
#       MA 02110-1301, USA.
chroots=('i686.1' 'x86_64.1' 'i686-testing.1' 'x86_64-testing.1' 
	 'i686.2' 'x86_64.2' 'i686-testing.2' 'x86_64-testing.2')

for i in ${chroots[@]}; do
	if [ -f /var/lock/make${i} ]; then
		chroot=$(echo -n "${i}" | sed -e 's|\.|_|' -e 's|-|_|')
		IFS=$'\n' read -r ${chroot} <<< ' In Use '
	else
		chroot=$(echo -n "${i}" | sed -e 's|\.|_|' -e 's|-|_|')
		IFS=$'\n' read -r ${chroot} <<< "        "
	fi
done

echo
echo '             i686     x86_64    i686/T   x86_64/T'
echo " Chroot 1 [${i686_1}][${x86_64_1}][${i686_testing_1}][${x86_64_testing_1}]"
echo " Chroot 2 [${i686_2}][${x86_64_2}][${i686_testing_2}][${x86_64_testing_2}]"

for i in ${chroots[@]}; do
	chroot=$(echo -n "${i}_msg" | sed -e 's|\.|_|' -e 's|-|_|')
	[ -f /var/lock/make${i} ] && echo -e "\n ${i}:\n  $(cat /var/lock/make${i})"
done

echo
