#!/bin/bash

trap '' 2 20

MUSER=$(echo $HOME | sed -e 's|/home/||')

if [ "$EUID" != "0" ]; then
	echo 'This script must be run as root.'
	exit 1
fi

if [ ! -f "$HOME/chroots/.x86_64" ]; then
	echo 'updating x86_64 chroot'
	touch $HOME/chroots/.x86_64
	mkarchroot -u $HOME/chroots/x86_64/root
	rm -f $HOME/chroots/.x86_64
else
	echo 'x86_64 chroot in use, skipping'
fi

if [ ! -f "$HOME/chroots/.x86_64-testing" ]; then
	echo 'updating x86_64 testing chroot'
	touch $HOME/chroots/.x86_64-testing
	mkarchroot -u $HOME/chroots/x86_64-testing/root
	rm -f $HOME/chroots/.x86_64-testing
else
	echo 'x86_64 testing chroot in use, skipping'
fi

if [ ! -f "$HOME/chroots/.i686" ]; then
	echo 'updating i686 chroot'
	touch $HOME/chroots/.i686
	linux32 mkarchroot -u $HOME/chroots/i686/root
	rm -f $HOME/chroots/.i686
else
	echo 'i686 chroot in use, skipping'
fi

if [ ! -f "$HOME/chroots/.i686-testing" ]; then
	echo 'updating i686 testing chroot'
	touch $HOME/chroots/.i686-testing
	linux32 mkarchroot -u $HOME/chroots/i686-testing/root
	rm -f $HOME/chroots/.i686-testing
else
	echo 'i686 testing chroot in use, skipping'
fi
