#!/bin/bash

if [ -z $1 ]; then
	echo 'No username specified.'
	exit 1
else
	UNAME=$1
fi

if [ "$EUID" != "0" ]; then
	echo 'This script must be run as root.'
	exit 1
fi

echo 'Adding user...'
useradd -m -G dev -s /bin/bash $UNAME
cp /usr/share/devadd/bashrc /home/${UNAME}/.bashrc

echo 'Setting up chroots...'
mkdir -p /home/${UNAME}/chroots/{i686{,-testing},x86_64{,-testing}}
mkarchroot -C /usr/share/devadd/pacman.conf /home/${UNAME}/chroots/x86_64/root base base-devel sudo
mkarchroot -C /usr/share/devadd/pacman-testing.conf /home/${UNAME}/chroots/x86_64-testing/root base base-devel sudo
linux32 mkarchroot -C /usr/share/devadd/pacman.conf /home/${UNAME}/chroots/i686/root base base-devel sudo
linux32 mkarchroot -C /usr/share/devadd/pacman-testing.conf /home/${UNAME}/chroots/i686-testing/root base base-devel sudo
for i in i686 i686-testing x86_64 x86_64-testing; do
	install -m 600 -o nobody -g root /usr/share/devadd/mirrorlist /home/${UNAME}/chroots/${i}/root/etc/pacman.d/mirrorlist
	install -m 644 /etc/resolv.conf /home/${UNAME}/chroots/${i}/root/etc/resolv.conf
	sed -i 's|#MAKEFLAGS="-j2"|MAKEFLAGS="-j5"|' /home/${UNAME}/chroots/${i}/root/etc/makepkg.conf
done

echo 'Setting up web-accessible directory...'
mkdir /srv/testing/${UNAME}

echo 'Verifying permissions...'
chown ${UNAME}:dev /home/${UNAME}/.bashrc
chown ${UNAME}:dev /srv/testing/${UNAME}

echo 'Operation complete.'
